language: generic
sudo: required
services:
    - docker
    
    
before_install:
    - docker build -t itay/docker-react -f docker_dev .
    
script:
    - docker run -e CI=true itay/docker-react npm run test -- --coverage